import type { Metadata, Viewport } from "next";
import { cookies } from "next/headers";
import { Suspense } from "react";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/lib/auth";
import { ALL_FONT_VARIABLES } from "@/lib/fonts";
import Navbar from "@/components/layout/Navbar";
import ConditionalFooter from "@/components/layout/ConditionalFooter";
import AskNaviFab from "@/components/layout/AskNaviFab";
import OptimizedBackgrounds from "@/components/ui/OptimizedBackgrounds";
import SkipLink from "@/components/layout/SkipLink";
import { AuthProvider } from "@/context/AuthContext";
import { NotificationProvider } from "@/context/NotificationContext";
import { MessagesProvider } from "@/context/MessagesContext";
import OnboardingGate from "@/components/auth/OnboardingGate";
import { ChatProvider } from "@/context/ChatContext";
import { ThemeProvider } from "@/context/ThemeContext";
import { LanguageProvider } from "@/context/LanguageContext";
import { PaywallProvider } from "@/context/PaywallContext";
import ErrorBoundary from "@/components/ErrorBoundary";
import { Toaster } from "@/hooks/useToast";
import AsyncStylesheet from "@/components/ui/AsyncStylesheet";
import { CookieConsentProvider } from "@/context/CookieConsentContext";
import CookieConsentBanner from "@/components/privacy/CookieConsentBanner";
import MobileScrollDamper from "@/components/ui/MobileScrollDamper";
import DailyRewardModal from "@/components/rewards/DailyRewardModal";
import HomepageIntro from "@/components/home/cosmic-intro/HomepageIntro";

const SITE_URL = "https://astranavi.com";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "AstraNavi | Vedic AI Astrology",
  description:
    "Bridging ancient Vedic wisdom with modern AI precision. Get personalized Kundli readings, daily horoscopes, and cosmic guidance from AI Vedic astrologers.",
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: SITE_URL,
    siteName: "AstraNavi",
    title: "AstraNavi | Vedic AI Astrology",
    description:
      "Bridging ancient Vedic wisdom with modern AI precision. Get personalized Kundli readings, daily horoscopes, and cosmic guidance from AI Vedic astrologers.",
    // OG image is generated by the file-convention route `opengraph-image.tsx`
    // and injected automatically — do not add an explicit `images` array here or
    // it will override the generator and point at a nonexistent static file.
  },
  twitter: {
    card: "summary_large_image",
    title: "AstraNavi | Vedic AI Astrology",
    description:
      "Bridging ancient Vedic wisdom with modern AI precision. Get personalized Kundli readings, daily horoscopes, and cosmic guidance from AI Vedic astrologers.",
    // Twitter image is generated by `twitter-image.tsx` (file convention).
  },
  // Icons resolve via file conventions: `favicon.ico` and `apple-icon.tsx` in
  // this directory are auto-detected and injected by Next.js.
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#0a0a1a",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get("theme")?.value;
  const theme = themeCookie === "light" ? "light" : "dark";
  // Read language cookie so server renders in the user's preferred language,
  // eliminating hydration mismatches between SSR and client.
  const languageCookie = cookieStore.get("NEXT_LOCALE")?.value || "en";
  // Resolve the session on the server so SessionProvider hydrates with the
  // authenticated state already known — no client-side round-trip, no
  // logged-out flash on refresh.
  // Wrapped in .catch(): if the JWT cookie is corrupt or the refresh flow
  // throws unexpectedly (e.g. token-reuse during a poisoned session), auth()
  // can throw and prevent the entire layout — including AuthProvider — from
  // rendering. That surfaces downstream as "useAuth must be used within an
  // AuthProvider". Falling back to null keeps the provider tree intact.
  const session = await auth().catch((e) => {
    console.error("[RootLayout] Failed to resolve session:", e);
    return null;
  });

  return (
    <html
      lang={languageCookie}
      className={`${ALL_FONT_VARIABLES} antialiased ${theme}`}
      suppressHydrationWarning
      
    >
      <head>
        {/* Pre-hydration guard: add `intro-pending` ONLY on the homepage, so the
            first-session cosmic intro can hide app chrome while it plays without
            blanking /login, /forgot-password, /reset-password, /logout, /privacy,
            /terms, or any deep link. The homepage intro gate removes the class on
            hydration; if JS/hydration fails the gate's fallback clears it. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `if(location.pathname==="/"){document.documentElement.classList.add("intro-pending")}`,
          }}
        />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <AsyncStylesheet href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </head>
      <body
        className="bg-background selection:bg-secondary selection:text-white overflow-x-hidden celestial-silk min-h-screen flex flex-col relative"
        suppressHydrationWarning
      >
        <ErrorBoundary>
          <SessionProvider session={session} refetchInterval={5 * 60}>
            <LanguageProvider initialLanguage={languageCookie}>
              <AuthProvider>
                <NotificationProvider>
                <MessagesProvider>
                <PaywallProvider>
                <ChatProvider>
                  <ThemeProvider>
                    <CookieConsentProvider>
                      <SkipLink />

                      <Suspense fallback={null}>
                        <OnboardingGate />
                      </Suspense>

                      <OptimizedBackgrounds />
                      <HomepageIntro />
                      <Toaster />
                      <DailyRewardModal />

                      <Navbar />
                      <script
                        type="application/ld+json"
                        dangerouslySetInnerHTML={{
                          __html: JSON.stringify({
                            "@context": "https://schema.org",
                            "@graph": [
                              {
                                "@type": "Organization",
                                "@id": `${SITE_URL}/#organization`,
                                name: "AstraNavi",
                                url: SITE_URL,
                                logo: `${SITE_URL}/favicon.ico`,
                                description: "Bridging ancient Vedic wisdom with modern AI precision.",
                                sameAs: [],
                              },
                              {
                                "@type": "WebSite",
                                "@id": `${SITE_URL}/#website`,
                                url: SITE_URL,
                                name: "AstraNavi",
                                publisher: { "@id": `${SITE_URL}/#organization` },
                                potentialAction: {
                                  "@type": "SearchAction",
                                  target: `${SITE_URL}/chat?q={search_term_string}`,
                                  "query-input": "required name=search_term_string",
                                },
                              },
                            ],
                          }),
                        }}
                      />
                      <main id="main-content" className="flex-grow relative z-10 dark:bg-transparent pt-[var(--navbar-height,64px)]">
                        {children}
                      </main>
                      <ConditionalFooter />
                      <AskNaviFab />
                      <CookieConsentBanner />
                      <MobileScrollDamper />
                    </CookieConsentProvider>
                  </ThemeProvider>
                  </ChatProvider>
                </PaywallProvider>
                </MessagesProvider>
                </NotificationProvider>
              </AuthProvider>
            </LanguageProvider>
          </SessionProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
